version: '3.10'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myscan
      POSTGRES_USER: slava
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://slava:password@db:5432/myscan

volumes:
  postgres_data: